sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "Kbf5N9W7Rxg/QN2FG+iY+PrTQtPuP15OQOHwwd5MezPzwukjMzqdQcyrNoEaVVY7Ut9jp2TwE3cSyauMla3jrg3psy2c22oaxgMTfK+zNrLevLyzLNc56B0Cq4r71W6cw1iNBkfBiPX88N5k3mR+OlIMIxoTJl7ayaw0lrIvJzG8YdGj6se10mxNaGGIOFT9uLdaGgm6fMp5TkKpu1hfZX38cuKnM1fPQ4lrgtw8QApDkDbl6J0kBN5/0gNtVrh9+Wrd8NSPQInN+dpe6OmBTlra/axWKJygOdhU6P0uCaohk1LDacZiUy8d4csnfiNNAtAyMb9GvtzsVYnf/VfL5HMNJf68Iprd1MKloXQP1nKqbhnNOR0Uqyx0oPPwYSMh0CafOGv7LcTBHOglTAL5IJK6z/VT4ZuC2nOc32+1YQRdgMBdOBy745/bIdoqHEKDBsdi4S8amMlAFXCIJQ5gggWhVbhB+YcKd+ZmWmRtcux+tBjNY3We7xq2svjczPIpmQDQajvr6usHvODRjGgmsQSvTYeJ2GsbHgJcDYo/cN6mYc1RPobrjKcoxDszF6f8djU7xmtl465iEUyWzQVaRX9JYlF+MCTsSVWzRh4tdmlUg8imzA9kFrbzCrbGg6h/TpXfoElObiq/oXs66emahE0k0r+Dln+9oDE/3gLgDNk="
  - secure: "BS4X2z66MFWck2qOc00IXmnDHE+bBRxXb81xwFmZ+1N6sRPNbziSYF2kypimmeJ8aKvE+cV3UsDRYN6CPOtU3JmUqKkvCovIZZiMFwS0dhG9L02l90msHj/AYWOWKH3WozuxSitNiTdvkuaeLTwBX+6rSwkDvyW/kpYCJasQw+Y9AlEciyXohe0z9mzZfkwlmuTOWViBqnK8f2p02LAYFeKLW3EugHOtFXnoXEfZOKcExlQKs3lapuyzX4Njhadcfeazfspq9Wc6/fp+RacgtY4Vwq1G5s7w5u3LKit0iZJTPIXdYnduHQ5/1hfeDrjvCnjRoj95/5JcTeg/FN+KNq+JWjGspfZd9tMZ+ynM8+yWGpI231kwbahgyn6YSfiXJGrip6GGDpb0f2bLgxt95bk/IzJURV2p1Sqs/PPkJ2H9Fa9ONhueKZdntM8mIFaDWGmjmad+bY1CIgifL1e/TI6fxkMn+ntb8wiVlTEp7UxT1uRElQb5R5sOvF8HmB9BgpWnoof0FIqRyVevx6ijrWznvQXQTDiC1z1g3sQYO9Gk2aWzPapX4G2Oqa6apUA6G3bqVhIS83JE9tQlt/NGyy3Zj/yXyt/wMNdei8uqtOWEOmwpNG96/R/W65Gu65Xvpvw5PFDMu+rZuKjhuHWqQ3uWSDfpL51WFwNqjLnBYZ4="
  - secure: "PZly+ZWYfOMvfoJ3PyE30MjSiIt3mPNJZ+BN0ytyQiDKbG1Rvp+ehsydk2Xj6xvbqQRWiU/cK3b9O7/vKUaIl75ftp5qk8yVFluYOacP/bSdPTY8eGndoV0/0Ix+6az6KXxZ8rX0LSSdnb0i85tKavrq31lV4VECtqtiYn+6tB8DcV8aycwDPSYgCbHxjQogkSzUfFUYYhGjGn84rIlTO2GiUZmDNGOiiD7MjMuQwvcWoiTXXI0P4gcOk6Rp+xxom5m7L9ZeBKDh8aZleczsq2ROzYQSKsYDn7AAi71GyJ0csHcbiDgJz3dNa/sAlHpXeXPkwbQCvQaj2VSM2pMGSINj37QqspQlAmClu8jcBziTScKaIiRI8dqOdJHsIJMlTN38HEK+hgsStRmxz9bHKVyiRX0+GvKgcmKfRm8Mkn4G09u+FGR20u5zrc6PT1WOlHpEvTEkgf4I+Jowxni1teofC921ERVbJrW53WSmQ8OldFN4BdJA3SJlI0ZIYMZUadWM/E/UsaZ30w5jzQJadBYJkK2RsdaneFvb9yZaCOK6uQtLqEpupm9fK61OVdXkki3h4sGyejL14GnFlS3B9j5rHDvHJh0ZghwCAXfN441JqTcqr1MSFp2e0ZJpvwGMJAhtL+kV1idrx3P2KB29U+KkxuHqn3bNcUywaERrcRQ="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
